swagger: '2.0'
basePath: /api
info:
  title: Dummy Api
  version: "0.0.1"

paths:
  '/stuff':
    get:
      tags: [stuff]
      operationId: zblaaaa.get_secret
      summary: Give me sugar sugar
      responses:
        200:
          description: Something secret

securityDefinitions:
  jwt:
    type: apiKey
    name: Authorization
    in: header
